export const referenceItems = [
  { name: "Akenerji", file: "akenerji.webp" },
  { name: "AKO", file: "ako.webp" },
  { name: "Albila", file: "albila.webp" },
  { name: "ASELSAN", file: "aselsan.webp" },
  { name: "Başkent Üniversitesi", file: "baskent-universitesi.webp" },
  { name: "Bilkent Holding", file: "bilkent-holding.webp" },
  { name: "Dorce", file: "dorce.webp" },
  { name: "Eczacıbaşı", file: "eczacibasi.webp" },
  { name: "Erdemir", file: "erdemir.webp" },
  { name: "Eti Bakır", file: "eti-bakir.webp" },
  { name: "Gen İlaç", file: "gen-ilac.webp" },
  { name: "Gürbağ", file: "gurbag.webp" },
  { name: "Hacettepe Üniversitesi", file: "hacettepe-universitesi.webp" },
  { name: "Halkbank", file: "halkbank.webp" },
  { name: "Hattuşa", file: "hattusa.webp" },
  { name: "KL Yapı", file: "kl-yapi.webp" },
  { name: "Koç Üniversitesi", file: "koc-universitesi.webp" },
  { name: "Kontrolmatik", file: "kontrolmatik.webp" },
  { name: "Konya Şeker", file: "konya-seker.webp" },
  { name: "Kredi Kayıt Bürosu", file: "kredi-kayit-burosu.webp" },
  { name: "Kuehne + Nagel", file: "kuehne-nagel.webp" },
  { name: "Limak", file: "limak.webp" },
  { name: "MKE", file: "mke.webp" },
  { name: "Onko Koçsel", file: "onko-kocsel.webp" },
  { name: "OTC", file: "otc.webp" },
  { name: "OYKA", file: "oyka.webp" },
  { name: "Özka", file: "ozka.webp" },
  { name: "Pınar Süt", file: "pinar-sut.webp" },
  { name: "Roketsan", file: "roketsan.webp" },
  { name: "SCHOTT", file: "schott.webp" },
  { name: "Şişecam", file: "sisecam.webp" },
  { name: "Şölen", file: "solen.webp" },
  { name: "TEİAŞ", file: "teias.webp" },
  { name: "Tepe Prefabrik", file: "tepe-prefabrik.webp" },
  { name: "TOFAŞ", file: "tofas.webp" },
  { name: "Torku", file: "torku.webp" },
  { name: "Toyota", file: "toyota.webp" },
  { name: "TPIC", file: "tpic.webp" },
  { name: "TÜBİTAK", file: "tubitak.webp" },
  { name: "Türk Telekom", file: "turk-telekom.webp" },
  { name: "VakıfBank", file: "vakifbank.webp" },
  { name: "Ziraat Bankası", file: "ziraat-bankasi.webp" },
];
